In [7]:
import numpy as np

# mini batch size 4

X = np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [4, 8, 12, 16],
    [2, 4, 6, 8],
    [1, 2, 3, 4],
])

# Suppose the network has structure
# 5, 3, 2

w2 = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
])

b2 = np.array([
    [1],
    [1],
    [1],
])
b2.shape

z = w2 @ X + b2
print(z)
np.exp(-z)

[[11 21 31 41]
 [11 21 31 41]
 [11 21 31 41]]


array([[1.67017008e-05, 7.58256043e-10, 3.44247711e-14, 1.56288219e-18],
       [1.67017008e-05, 7.58256043e-10, 3.44247711e-14, 1.56288219e-18],
       [1.67017008e-05, 7.58256043e-10, 3.44247711e-14, 1.56288219e-18]])

In [13]:
# Suppose the network has structure
# 5, 3, 2

# neurons in 2nd layer x mini batch size
error_2 = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
])

# neurons in 1st layer x mini batch size
a_1 = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

a_1.sum(axis=0)
b = np.array([0, 1, 2, 3])
np.expand_dims(b, axis=1)

array([[0],
       [1],
       [2],
       [3]])